language: node_js
node_js: 
  - "7"
branches:
  only:
    - v0.1
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - cd functions/
  - npm install
script: 
  - firebase deploy --only functions --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change